name: Main Workflow

on: [push]

jobs:
  call-reusable-workflow:
    uses: vineeth12345/workflows/.github/workflows/build-and-push-ECR.yml@main
    with:
      caller_repo: ${{ github.repository }}
      # aws_region: us-east-1
      # ecr_repository: my-ecr-repo
